
#
#### Exercises

#
#####1. What are the three requirements when naming an R package?

Ans: The three requirements when naming an R package is that the name can only consist of letters, number, and period, and no hyphens or underscores in the package name. It must start with a letter and can't end with a period.


#
#####2. Why is it a bad idea to name your package with a "."?

Ans: Because it has confusing connotations (i.e., file extension or S3 method).


#
#####3. What is the difference between devtools::install_github and install.packages?

Ans: `devtools::install_github()` downloads a source package from GitHub, runs `build()` to make vignettes, and then uses `R CMD INSTALL` to do the install.  `install.packages()` is used to download and install binary packages built by CRAN.

 
#
#####4. What is the difference between devtools::build and devtools::install?

Ans: `devtools::build()` is a wrapper for `R CMD build` that turns source packages into bundles. `devtools::install()` is an effective wrapper for `R CMD INSTALL`.


#
#####5. What is the difference between devtools::load_all and library?

Ans: `devtools::load_all()` checks that the packages are installed. `library()` loads and attaches an installed package devtools to the search path.


#
#####6. What is the difference between Suggests and Imports?

Ans: `Imports` shows that listed packages that must be present for your package to work. `Suggests` shows that your package can use the listed packages but doesn’t require them. 


#
#####7. What is the importance of dontrun?

Ans: dontrun{} allows you to include code in the example that is not run. 


#
#####8. Why do packages have versions?

Ans: Because R packages are keeping developed, they can have more than one version. It’s always better to specify the version and to require a version greater than or equal to the version you’re currently using.


#
#####9. What does moving from v1.0.1 to v2.0.0 mean? What does moving from v1.0.1 to v1.0.2 mean?

Ans: 

v2.0.0 is a newer version than v.1.0.1. For v.2.0.0, the package had been made a major modification.

Moving from v.1.0.1 to v.1.0.2 means that v.1.0.1 was patched, and the patched package was versioned as v.1.0.2


# 
#####10. What does v1.0.1.9000 mean?

Ans: It means it is the development version of v1.0.1

